version: '3'

services:
    scmxpert:
     image: dnetworkhub/scmxpert:latest 
     ports:
       - "8001:8001"

    zookeeper:
      image: 'bitnami/zookeeper:latest'
      ports:
       - "2181:2181"
      depends_on:
        - scmxpert
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes

    kafka:
      image: 'bitnami/kafka:latest'
      ports:
       - "9092:9092"
      depends_on:
       - zookeeper
      environment:
       - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
       - ALLOW_PLAINTEXT_LISTENER=yes
       - KAFKA_HEAP_OPTS=-Xmx1G

    server:
     image: dnetworkhub/server:latest 
     ports:
       - "8005:8005"
     depends_on:
       - kafka

    producer:
     image: dnetworkhub/producer:latest
     environment:
       - bootstrap_servers=kafka:9092
       - host=server
     depends_on:
       - server

    consumer:
     image: dnetworkhub/consumer:latest
     environment:
       - bootstrap_servers=kafka:9092
     depends_on:
       - producer
                                